### ISSUE TITLE
Decide on backup details

### ISSUE THREAD

**Issue by danielnordh** [bdgwallet/dailywallet#1]
What import formats should we support? (note, can’t generate ExtendedKeyInfo from anything but mnemonic)
- Recovery phrase (check guide for best practice input format)
- Private key
- Xpub (for watch only)
- Descriptor?

Response from @afilini in bdk discord:

"the full descriptor (which includes private keys as xprvs) is the most "conservative" thing to backup, i.e. if you have the descriptor you can always restore the wallet
for some wallet it can make sense to just backup the keys + a "name" or some kind of identifier of a descriptor template, which then allows you to reconstruct the descriptor
for example if you wallet is just a multisig wallet, you could backup the keys + the threshold and then you can always reconstruct the descriptor later (at least with sortedmulti, otherwise you need to also backup the order of the keys)
an alternative to the first approach (full descriptor with private keys) is to backup a descriptor with only public keys plus the private key as a menmonic separtely: this would in a way decrease how "sensitive"( in terms fo security) the descriptor is. since it only contains public keys it cannot be used to steal funds, just at most to monitor the wallet (privacy leak)
the reason i'm saying this is that i think it would be pretty hard to ask the average user to write down a full descriptor by hand. but you also don't want to print/store digitally a string that contains private keys. so separating the two has the nice benefit that you could print a qrcode with the watch-only descriptor and then write down the mnemonic on the same piece of paper
the downside is that the user needs to understand that it needs both the descriptor and mnemonic to restore the wallet, which is not normally the case for single sig wallets (you only backup the mnemonic)"

Should probably do:
- Descriptor, to have accurate wallet ready to go (call it onchaindescriptor, have separate for lightning)
- xprv (for now, let's handle xpub for read only wallets later)
- Recovery phrase, to enable export (but will need also derivation info)

Edge cases:
- A wallet imported with a xprv or xpub will not have a recovery phrase
- Should backup separate between xprv and xpub or store in same 'slot'?

**Comment by danielnordh** [comment]
For now, created a new class called `KeyBackup` with the following:

```swift
public var mnemonic: String
public var xprv: String
public var descriptor: String
```

**Comment by afilini** [comment]
Mnemonic and xprv are basically the same thing encoded in different ways, so you probably don't need to backup both

**Comment by danielnordh** [comment]
> Mnemonic and xprv are basically the same thing encoded in different ways, so you probably don't need to backup both

I can't generate the mnemonic from the xprv though right?

**Comment by afilini** [comment]
Yes sorry, I should have explained myself better.

It is a one way function, so you can get the xprv from the mnemonic but not the other way around. What I meant to say is that you should probably just backup the mnemonic instead of both, because you can always compute the other on demand
